#
# Kitty config
#

# theme 
include catppuccin-mocha.conf

# font
font_family        family="JetBrainsMono Nerd Font"
font_size          11.0
bold_font          auto
italic_font        auto
bold_italic_font   auto
disable_ligatures  always

# cursor
cursor_shape block
shell_integration no-cursor

# close confirm
confirm_os_window_close 0

# opacity
background_opacity 1.0
